# Generated by Django 4.2.6 on 2023-10-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_messages', '0001_initial'),
    ]

    operations = [
    ]
