# Generated by Django 4.2.6 on 2023-10-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_load_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publisher', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_url_s', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_url_m', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_url_l', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
