# Generated by Django 4.2.6 on 2023-10-28 03:52

from django.db import migrations
from django.core.management import call_command
def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "initial_data.json")

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231028_1043'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
