# Generated by Django 4.2.6 on 2023-10-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20231028_1052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book_book',
        ),
    ]
