<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-28 03:57
=======
# Generated by Django 4.2.6 on 2023-10-28 02:57
>>>>>>> 9fbc04355f8b4b5f0cc8795b0f08a1d9a34492f0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Profile',
=======
            name='User_profile',
>>>>>>> 9fbc04355f8b4b5f0cc8795b0f08a1d9a34492f0
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
