# Generated by Django 4.2.6 on 2023-10-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
    ]
