# Generated by Django 4.2.6 on 2023-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
