# Generated by Django 4.2.6 on 2023-12-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discussion', '0002_header_rating'),
    ]

    operations = [
    ]
