# Generated by Django 4.2.6 on 2023-12-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discussion', '0003_auto_20231219_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
